import Head from 'next/head';
import { useRouter } from 'next/router';
import { HydrationProvider, Server, Client } from 'react-hydration-provider';
import graphCmsClient from '../lib/graphCmsClient';
import { GraphQLClient, gql } from 'graphql-request';
import Link from 'next/link';

const QUERY = gql`
  query IndexPageQuery($locale: Locale!) {
    products(locales: [$locale]) {
      id
      locale
      name
      price
      images {
        height
        url
        width
      }
      imagesqwe {
        height
        width
        url
      }
      slug
    }
  }
`;

export async function getStaticProps({ locale }) {
  const { products } = await graphCmsClient.request(QUERY, { locale })

  return {
    props: {
      products,
    },
  }
}

export default function Home({ products }) {
  const router = useRouter();

  console.log(products);

  return (
    <>
      <Head>
        <title>jezici</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <HydrationProvider> */}
        {/* <Server> */}
        <h1>ajdeeeleeppooo</h1>
        <div>
          {/* <pre>{JSON.stringify(products, null, 2)}</pre> */}
          <div>
            {products.map((product) => (
              <div key={product.id}>
                <Link href={product.id} locale={router.locale}>

                  <h1>{product.name}</h1>

                </Link>
              </div>
            ))}
          </div>
        </div>
        {/* </Server> */}
        {/* </HydrationProvider> */}
      </main>
    </>
  );
}
